# Generated by Django 5.1.1 on 2024-09-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='superhost',
            field=models.BooleanField(default=False, verbose_name='SuperHost'),
        ),
    ]
