# Generated by Django 5.1.2 on 2024-10-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_superhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('krw', 'KRW'), ('irr', 'IRR')], default='usd', max_length=5, verbose_name='Currency'),
        ),
    ]
