# Generated by Django 5.1.1 on 2024-09-20 15:31

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(max_length=140, verbose_name='Name')),
                ('desciption', models.TextField(help_text='Enter Your Decription of the Room Here', verbose_name='Descpription')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('address', models.CharField(max_length=1400, verbose_name='Address')),
                ('bed', models.SmallIntegerField(verbose_name='Bed')),
                ('bedroom', models.SmallIntegerField(verbose_name='Bedroom')),
                ('guest', models.SmallIntegerField(verbose_name='Guest')),
                ('check_in', models.TimeField(verbose_name='Check In')),
                ('check_out', models.TimeField(verbose_name='Check Out')),
                ('instant_book', models.BooleanField(default=False, verbose_name='Instant Book')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
