# Generated by Django 5.1.1 on 2024-09-20 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomtype_alter_room_options_alter_room_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Room Amenity',
                'verbose_name_plural': 'Room Amenities',
            },
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Room Facility',
                'verbose_name_plural': 'Room Facilities',
            },
        ),
        migrations.CreateModel(
            name='RoomRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Room Rule',
                'verbose_name_plural': 'Room Rules',
            },
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'Room Type', 'verbose_name_plural': 'Room Types'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_amenity',
            field=models.ManyToManyField(blank=True, to='rooms.roomamenity', verbose_name='Room Amenities'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.roomfacility', verbose_name='Room Facility'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_rule',
            field=models.ManyToManyField(blank=True, related_name='room_rules', to='rooms.roomrule', verbose_name='Room Rule'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.roomtype', verbose_name='Room Type'),
        ),
    ]
