# Generated by Django 5.1.1 on 2024-09-20 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomamenity_roomfacility_roomrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, max_length=150, null=True, verbose_name='Caption')),
                ('image', models.ImageField(upload_to='rooms/room-images/', verbose_name='Image')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_photo',
            field=models.ManyToManyField(related_name='images', to='rooms.roomphoto', verbose_name='Room Image'),
        ),
    ]
