# Generated by Django 5.1.1 on 2024-09-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roomphoto_room_room_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_photo',
        ),
    ]
