# Generated by Django 5.1.1 on 2024-09-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_room_room_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, max_length=150, null=True, verbose_name='Caption')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RoomPhoto',
        ),
    ]
