# Generated by Django 5.1.1 on 2024-09-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_roomimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'Room Image', 'verbose_name_plural': 'Room Images'},
        ),
    ]
