# Generated by Django 5.1.1 on 2024-09-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_roomimage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_facility',
        ),
        migrations.AddField(
            model_name='room',
            name='room_facility',
            field=models.ManyToManyField(blank=True, null=True, related_name='room_facility', to='rooms.roomfacility', verbose_name='Room Facility'),
        ),
    ]
