# Generated by Django 5.1.1 on 2024-09-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_remove_room_room_facility_room_room_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_facility',
            field=models.ManyToManyField(blank=True, related_name='room_facility', to='rooms.roomfacility', verbose_name='Room Facility'),
        ),
    ]
