# Generated by Django 5.1.1 on 2024-09-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_room_room_facility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='desciption',
            new_name='description',
        ),
    ]
