# Generated by Django 5.1.1 on 2024-09-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_room_bath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_rule',
            new_name='house_rule',
        ),
    ]
