# Generated by Django 5.1.1 on 2024-10-24 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_rename_room_rule_room_house_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_amenity',
            field=models.ManyToManyField(blank=True, related_name='room_amenities', to='rooms.roomamenity', verbose_name='Room Amenities'),
        ),
    ]
