# Generated by Django 5.1.1 on 2024-10-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_alter_room_host_alter_room_room_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='house_rule',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.roomrule', verbose_name='Room Rule'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_amenity',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.roomamenity', verbose_name='Room Amenities'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_facility',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.roomfacility', verbose_name='Room Facility'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.roomtype', verbose_name='Room Type'),
        ),
    ]
