# Generated by Django 5.1.1 on 2024-10-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_alter_roomimage_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomAmenity',
            new_name='Amenity',
        ),
        migrations.RenameModel(
            old_name='RoomFacility',
            new_name='Facility',
        ),
        migrations.RenameModel(
            old_name='RoomRule',
            new_name='Rule',
        ),
    ]
