# Generated by Django 5.1.1 on 2024-10-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_rename_roomamenity_amenity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Rule', 'verbose_name_plural': 'Rules'},
        ),
    ]
