# Generated by Django 5.1.1 on 2024-10-25 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_check_in_alter_review_cleanliness_and_more'),
        ('rooms', '0017_alter_roomimage_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.room', verbose_name='Room'),
        ),
    ]
